### ISSUE TITLE
Inline datepicker should follow styling of inputs inside fieldcontain

### ISSUE THREAD

**Issue by bjartekv** [arschmitz/jquery-mobile-datepicker-wrapper#10]
The inline datepicker doesn't change it's styling when inside fieldcontain.

![croppercapture 3](https://f.cloud.github.com/assets/122742/2119827/09971ac2-918e-11e3-993e-da7a1a6cb6ad.png)

I've attempted to fix the styling a bit http://jsbin.com/uzaret/1300/edit

``` css
    .ui-field-contain > div.hasDatepicker {
      margin: 8px 0;
    }  
    @media (min-width: 28em) {
      .ui-field-contain > div.hasDatepicker {
        margin: 8px 0 8px 22%;
      } 
      div.hasDatepicker + label 
      {
        clear: left;
      }
    }
```
